### ISSUE TITLE
moving head control

### ISSUE THREAD

**Issue by martin3000** [spacemanspiff2007/PyArtNet#15]
Is it possible to control a movig had spot light with pyArtNet?

**Comment by spacemanspiff2007** [comment]
Does the moving head spot behave different than other dmx devices?
You can set values of channels directly and you can run fades on channels.
If that is sufficient you can also control a moving head.

**Comment by martin3000** [comment]
Maybe that is sufficient. Is there an example of how to send a value on a channel?

**Comment by spacemanspiff2007** [comment]
Just set a fade with duration 0

**Comment by martin3000** [comment]
ok, something like this:
`channel.add_fade( [127,100,10], 0 )`
