### ISSUE TITLE
Feature request: A way to skip all the fading and just set pixel values

### ISSUE THREAD

**Issue by raldi** [spacemanspiff2007/PyArtNet#23]
Sorry if I'm missing something, but is there any way to use this library to just say "Set these pixels to these values, immediately, and keep them that way"? As far as I can tell, my only option is to fade in my desired colors, and then have them fade out even though I don't want them to.

**Comment by spacemanspiff2007** [comment]
Just add a fade with the desired pixel values with duration 0?

**Comment by raldi** [comment]
Maybe I'm doing something wrong, but when I try that, they just fade right back out again.

**Comment by spacemanspiff2007** [comment]
Have you started the periodic refresh service? Some controllers turn the light off after x seconds of no new message.
