### ISSUE TITLE
Request / question: Is RDM possible?

### ISSUE THREAD

**Issue by himijendrix24** [spacemanspiff2007/PyArtNet#27]
Is there any way to get RDM information of devices (more precise: a temperature value of led controllers)? 
The only possibility I see is using openlighting and its pythonAPI.
However I was looking for a more lightweight approach with a single python-artnet library.

Please close if not possible  / planned and maybe add this information.

**Comment by spacemanspiff2007** [comment]
No - currently there is no support for RDM support.
However I'd gladly accept a PR that adds support for it.
