### ISSUE TITLE
Feedback rework

### ISSUE THREAD

**Issue by spacemanspiff2007** [spacemanspiff2007/PyArtNet#30]
Hi,

I've done a huge [rework](https://github.com/spacemanspiff2007/PyArtNet/tree/rework) and I'd like to get some feedback on it.

The fade task now starts automatically, the refresh task however must still be started manually.
I'm unsure if I should keep it that way or if it should be started automatically.

There is an additional `channel.set_value([0])` for the channel to immediately set values without a fade.

I've also added support for sACN E1.31 and KiNet, however I can not test it so some feedback would be nice.

Output correction is now set with `node.set_output_correction(func)` `universe.set_output_correction(func)` `channel.set_output_correction(func)`

I'm pining a couple of contributors who either reported issues or did some tests in the past.
It would be really nice to get some feedback before I finalize everything and push to pypi
@MicahMeadows @hynekcer @Breina @corb3000 @sdegrande

**Comment by Breina** [comment]
Fantastic! Thanks for the great work!

>The fade task not starts automatically, the refresh task however must still be started manually.
>I'm unsure if I should keep it that way or if it should be started automatically.

Best keep it manually for now. Some of the HomeAssistant DMX users have additional DMX controllers, which would interfere if refreshing is used. So I'd prefer to keep it as an option for now.

>I've also added support for sACN E1.31 and KiNet, however I can not test it so some feedback would be nice.

I should be able to test sACN, but not immediately working atm. Will keep you posted.

**Comment by Breina** [comment]
Haven't fully gotten it working yet, but 2 notes on `node_sacn.py` already:

* `self._send_data(packet)` should probably be `self._send_data(base_packet + packet)`.
* `packet.extend(values)                           # 1-513 | Property Values` skips the _START Code_ byte, and because of this the packet-size bytes everywhere are off by 1 from what I can tell. 
![image](https://user-images.githubusercontent.com/3009914/208782115-9df082bf-c29f-4bf9-b188-5bff4ef148c1.png)

**Comment by spacemanspiff2007** [comment]
> skips the START Code byte, and because of this the packet-size bytes everywhere are off by 1 from what I can tell.

Good catch! I've pushed an update which fixes that

> `self._send_data(packet)` should probably be `self._send_data(base_packet + packet)`.

No - `self._send_data(packet)` is correct

---

Could you generate a working and correct sACN UDP message and post it here as a hex? Then I can add a test that ensures it's built properly.

**Comment by Breina** [comment]
>No - self._send_data(packet) is correct

In that case I think that there's a missing step to append `base_packet` to it. The `packet` only contains the Framing and DMP layer:

![image](https://user-images.githubusercontent.com/3009914/208921268-ba1b37eb-0f15-42ee-85b9-c7d3a80b40fe.png)

>Could you generate a working and correct sACN UDP message and post it here as a hex? Then I can add a test that ensures it's built properly.

### PyArtNet

#### Sample code
```
import asyncio
from src.pyartnet import SacnNode, ArtNetNode

async def sacn():
    node = SacnNode("192.168.1.15", 5568)
    await node.start()
    universe = node.add_universe(1)
    channel = universe.add_channel(start=1, width=4)
    channel.set_values([255, 128, 3, 4])

asyncio.run(sacn())
```

#### Payload (`base_packet` + `packet`)

```
0000   00 01 00 00 41 53 43 2d 45 31 2e 31 37 00 00 00  ....ASC-E1.17...
0010   70 72 00 00 00 04 ee 3f 95 29 11 32 44 90 8c c3  pr.....?.).2D...
0020   1b f4 e7 31 6f 25 70 5c 00 00 00 02 50 79 41 72  ...1o%p\....PyAr
0030   74 4e 65 74 00 00 00 00 00 00 00 00 00 00 00 00  tNet............
0040   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0050   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0060   00 00 00 00 00 00 00 00 00 00 00 00 64 00 32 00  ............d.2.
0070   01 00 00 41 53 43 2d 45 31 2e 31 37 00 00 00 70  ...ASC-E1.17...p
0080   72 00 00 00 04 ee 3f 95 29 11 32 44 90 8c c3 1b  r.....?.).2D....
0090   f4 e7 31 6f 25 70 5c 00 00 00 02 50 79 41 72 74  ..1o%p\....PyArt
00a0   4e 65 74 00 00 00 00 00 00 00 00 00 00 00 00 00  Net.............
00b0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00c0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00d0   00 00 00 00 00 00 00 00 00 00 00 64 00 32 01 00  ...........d.2..
00e0   00 01 70 0f 02 a1 00 00 00 01 00 05 00 ff 80 03  ..p.............
00f0   04                                               .
```

### [sACNsender](https://pypi.org/project/sacn/)

#### Sample code

```
import time
from sacn import sACNsender

sender = sACNsender()
sender.start()
sender.activate_output(1)
sender[1].multicast = False
sender[1].destination = "192.168.1.15"
sender[1].dmx_data = (255, 128, 3, 4)

time.sleep(10)
sender.stop()
```

#### Payload

```
0000   00 10 00 00 41 53 43 2d 45 31 2e 31 37 00 00 00  ....ASC-E1.17...
0010   72 6e 00 00 00 04 41 68 f5 2b 1a 7b 2d e1 17 12  rn....Ah.+.{-...
0020   e9 ee 38 3d 22 58 72 58 00 00 00 02 64 65 66 61  ..8="XrX....defa
0030   75 6c 74 20 73 6f 75 72 63 65 20 6e 61 6d 65 00  ult source name.
0040   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0050   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0060   00 00 00 00 00 00 00 00 00 00 00 00 64 00 00 00  ............d...
0070   00 00 01 72 0b 02 a1 00 00 00 01 02 01 00 ff 80  ...r............
0080   03 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0090   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00a0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00b0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00c0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00d0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00e0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00f0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0100   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0110   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0120   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0130   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0140   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0150   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0160   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0170   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0180   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0190   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
01a0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
01b0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
01c0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
01d0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
01e0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
01f0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0200   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0210   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0220   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0230   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0240   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0250   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0260   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0270   00 00 00 00 00 00 00 00 00 00 00 00 00 00        ..............
```

**Comment by spacemanspiff2007** [comment]
> In that case I think that there's a missing step to append `base_packet` to it. The `packet` only contains the Framing and DMP layer:

``_send_data`` will append data to the base_packet.

---

It seems `sACNsender` will always send the whole universe. Can you set the [names](https://github.com/spacemanspiff2007/PyArtNet/blob/4cec64a2d887a858b695ff4c64b3621628262ef1/src/pyartnet/impl_sacn/node.py#L35) to the same value and add channel 512 so the frames can be compared?

**Comment by Breina** [comment]
Ah my bad, didn't spot that!

#### Test code

```
async def sacn():
    node = SacnNode("192.168.1.15", 5568, cid=bytes([0x41, 0x68, 0xf5, 0x2b, 0x1a, 0x7b, 0x2d, 0xe1, 0x17, 0x12, 0xe9, 0xee, 0x38, 0x3d, 0x22, 0x58]), source_name="default source name")
    await node.start()
    universe = node.add_universe(1)
    channel = universe.add_channel(start=1, width=4)
    channel.set_values([0, 128, 3, 4])
    universe.add_channel(512, 1)
```

#### Result

```
0000   00 01 00 00 41 53 43 2d 45 31 2e 31 37 00 00 00  ....ASC-E1.17...
0010   72 6e 00 00 00 04 41 68 f5 2b 1a 7b 2d e1 17 12  rn....Ah.+.{-...
0020   e9 ee 38 3d 22 58 72 58 00 00 00 02 64 65 66 61  ..8="XrX....defa
0030   75 6c 74 20 73 6f 75 72 63 65 20 6e 61 6d 65 00  ult source name.
0040   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0050   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0060   00 00 00 00 00 00 00 00 00 00 00 00 64 00 32 01  ............d.2.
0070   00 00 01 72 0b 02 a1 00 00 00 01 02 00 00 00 80  ...r............
0080   03 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0090   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00a0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00b0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00c0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00d0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00e0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00f0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0100   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0110   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0120   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0130   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0140   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0150   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0160   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0170   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0180   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0190   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
01a0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
01b0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
01c0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
01d0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
01e0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
01f0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0200   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0210   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0220   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0230   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0240   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0250   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0260   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0270   00 00 00 00 00 00 00 00 00 00 00 00 00 00        ..............
```

#### Diff (left is yours)

![image](https://user-images.githubusercontent.com/3009914/208928801-a91e08ad-da78-40d9-8728-1f3cea3af911.png)

**Comment by spacemanspiff2007** [comment]
We're getting there! I made some more changes - I hope it works now.
How did you generate this nice output?
Could you provide the whole hex with .hex() method, too?

**Comment by Breina** [comment]
Nice that works! :) Thanks!

The pretty output was like this with WireShark:

![image](https://user-images.githubusercontent.com/3009914/208952425-850da60d-240d-4e11-9e78-e4f065fb2d7c.png)

Hex version of this for completeness:

`001000004153432d45312e3137000000726e000000044168f52b1a7b2de11712e9ee383d225872580000000264656661756c7420736f75726365206e616d6500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000064003200000001720b02a100000001020100ff80030400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000`

---

The above is with a channel on 255, without it it does seem to cut off the last few channels in steps:

| Channels defined | Result         |
|------------------|----------------|
| 1                | Nothing        |
| 2                | Nothing        |
| 3                | Nothing        |
| 4                | Nothing        |
| 5                | Updates [1, 2] |
| 6                | Updates [1, 2] |
| 7                | Updates [1, 4] |
| 8                | Updates [1, 4] |
| 9                | Updates [1, 6] |
| 10               | Updates [1, 6] |

Example for 10 channels:

```
channel = universe.add_channel(start=1, width=10)
channel.set_values([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
```

`001000004153432d45312e31370000007078000000044168f52b1a7b2de11712e9ee383d225870620000000264656661756c7420736f75726365206e616d6500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000064003200000001701502a100000001000b000102030405060708090a`

**Comment by spacemanspiff2007** [comment]
> Nice that works! :) Thanks!

Great! Could you play around with the fades a little bit to make sure everything is as desired?
Any other feedback would be appreciated, too!

**Comment by spacemanspiff2007** [comment]
> The above is with a channel on 255, without it it does seem to cut off the last few channels in steps:

What do you mean by that? Once you have added a channel everything up until this channel should be sent

**Comment by Breina** [comment]
Having trouble testing the fades currently, is there a replacement for `channel.wait_till_fade_complete()`?

>What do you mean by that?

Your implementation is correct, my device appears to ignore the last 4 bytes (ENTTEC DIN Ethergate Firmware V1.2). Going to contact them about it.

---

@jjhuff Any chance you are able to test the KiNet support here?

**Comment by spacemanspiff2007** [comment]
> Having trouble testing the fades currently, is there a replacement for `channel.wait_till_fade_complete()`?

Not yet. But there is a callback on the channel that will be called when the fade is complete:
https://github.com/spacemanspiff2007/PyArtNet/blob/d6da54ee0899dafff80bda6b94457437da7e7836/src/pyartnet/base/channel.py#L81

**Comment by Breina** [comment]
@spacemanspiff2007 Is it possible to catch exceptions coming from `self._socket.sendto` in this version?

It's quite verbose if the socket is unreachable: https://github.com/Breina/ha-artnet-led/issues/6

**Comment by spacemanspiff2007** [comment]
So what would you expect? 
I think it'll be good to log something because clearly something is not working properly.
A Callback that takes the exception would be one way, but then you'd have to make sure that something is getting logged ...

**Comment by Breina** [comment]
Maybe a callback yes? Or maybe just stop trying after N times if it isn't working.

**Comment by spacemanspiff2007** [comment]
I'm unsure what would be a good method without introducing huge overhead.
Currently I'm logging the node name so it's clear which node is creating the issues:
https://github.com/spacemanspiff2007/PyArtNet/blob/d6da54ee0899dafff80bda6b94457437da7e7836/src/pyartnet/base/base_node.py#L160

**Comment by spacemanspiff2007** [comment]
@Breina 
I've did some more rework and at least the refresh task has a small timeout logic so the error messages should not be too much.
For active fades however I don't have any smart solution.
Would mind looking at it again and share you thoughts?

**Comment by Breina** [comment]
I think it's perfect! :)

I particularly like the abstraction of `CREATE_TASK` in `background_task.py`, I will be using that.

All my wishes are fulfilled, thanks man! :)

**Comment by Breina** [comment]
Congrats with the 1.0.0 release! :)
