### ISSUE TITLE
Discussion: effects

### ISSUE THREAD

**Issue by Breina** [spacemanspiff2007/PyArtNet#40]
HA has the possibility of adding arbitrary effects on a per-light basis. As such:

![image](https://user-images.githubusercontent.com/3009914/221350403-626b8bbd-4203-478b-8392-3821f6aa950a.png)

I think it might be a fun feature to implement in PyArtNet, given that it's already doing the transitional animations. It has the threading infrastructure to handle this as well.

Might make more sense to do it externally though, just poking and prodding here first. :)

**Comment by spacemanspiff2007** [comment]
You can already do that. Just create your own Fade implementation which inherits from `FadeBase` and pass it to `set_fade`

**Comment by Breina** [comment]
Awesome! :)
