### ISSUE TITLE
too many files open

### ISSUE THREAD

**Issue by kleurbleur** [spacemanspiff2007/PyArtNet#43]
version used: pyartnet 1.0.1
python version: 3.9.6 via venv 
error: OSError: [Errno 24] Too many open files

I get an error while executing code below.  When I use add_fade instead everything runs smooth, although I do get some spikes to 255 in the ArtNet output.

https://pastebin.com/pCkGWc9x

**Comment by spacemanspiff2007** [comment]
Why do you think creating the node, the universe and the channel in a while loop is a good idea.
For every run you create the objects. 
There are working examples in the documentation - please take a look at them.

**Comment by kleurbleur** [comment]
Right, thanks for the feedback. I'm new to asyncio and I tried the most basic setup from your examples for a continuous output. Managed to get it now!
