### ISSUE TITLE
multiple universes using add_universe

### ISSUE THREAD

**Issue by zenonymous** [spacemanspiff2007/PyArtNet#7]
Hi, I am trying to set up multiple universes using PyArtNet like:

    universe = node.add_universe(0)
    multiverse = node.add_universe(1)

however only the first universe I add seems to respond: what am I doing wrong? Thanks in advance!

**Comment by zenonymous** [comment]
nevermind, turns out creating a node foreach universe does the trick 👍

**Comment by spacemanspiff2007** [comment]
It is possible to use multiple universes with on node.
Can you please investigate further why this wouldn't work for you?

**Comment by zenonymous** [comment]
> It is possible to use multiple universes with on node.
> Can you please investigate further why this wouldn't work for you?

sure thing, could you maybe provide a piece of example code how this should work according to you?

I have been trying different approaches regarding adding multiple universes to a node and each time it resulted in only the first defined universe working. This project looks awesome and I really want to use it to control leds for a lightart thingie this year but sometimes it takes some figuring out how to do things 👍

**Comment by spacemanspiff2007** [comment]
Ah yes - that's actually a bug. I already found it.
