### ISSUE TITLE
add_fade invalid assert

### ISSUE THREAD

**Issue by dturpin74** [spacemanspiff2007/PyArtNet#8]
seems like this line is problematic
dmx_channel.py line 91

 assert 0 <= k.val_target <= 255 ** self._CHANNEL_SIZE

this does not work when using 16bit+ channels.  The upper limit of fade value would be 65025 or 0xFE01 instead of the expected 0xFFFF

Value should be compared against (256 ** channel_size) - 1 instead

**Comment by spacemanspiff2007** [comment]
Thanks for your report - I'll fix it right away!
