### ISSUE TITLE
Broadcast Artnet

### ISSUE THREAD

**Issue by USW-Adam** [spacemanspiff2007/PyArtNet#9]
Hi, whenever I try to broadcast artnet across a network it just doesn't work (target ip of 255.255.255.255). If I keyboard break I get this error:

Traceback (most recent call last):
  File "shortArtnetTest.py", line 28, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1739, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
Task exception was never retrieved
future: <Task finished coro=<ArtNetNode.__worker() done, defined at /usr/local/lib/python3.7/dist-packages/pyartnet/artnet_node.py:63> exception=PermissionError(13, 'Permission denied')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pyartnet/artnet_node.py", line 76, in __worker
    self.update()
  File "/usr/local/lib/python3.7/dist-packages/pyartnet/artnet_node.py", line 129, in update
    self._socket.sendto(packet, (self.__host, self.__port))
PermissionError: [Errno 13] Permission denied

If I target specific IPs instead of broadcast everything works fine, any help would be much appreciated!
Thanks!

**Comment by spacemanspiff2007** [comment]
Can you try with admin right?

**Comment by USW-Adam** [comment]
If I try as sudo (I'm on a raspberry pi) It still doesn't work, and even if I enter root it doesn't work, both spit out the same error

**Comment by USW-Adam** [comment]
Quick update, it's definitely something I've done wrong with the raspberry pi because after installing on windows and running it I can broadcast absolutely fine.

**Comment by spacemanspiff2007** [comment]
Thanks for the update - I'm closing this.

**Comment by USW-Adam** [comment]
Just for anyone else who ever has this problem, if you open up the artnet_node.py file and under line 32 (`self._socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)  # UDP`) add the line
`self._socket.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)`. I think this is something to do with the way raspberry pi's handle broadcast packets, which is why it worked fine on Windows.

**Comment by spacemanspiff2007** [comment]
Does this work on windows, too?

**Comment by USW-Adam** [comment]
Yes it does, for me at least 😅

**Comment by spacemanspiff2007** [comment]
Then I'll integrate it into pyartnet

**Comment by spacemanspiff2007** [comment]
Would you mind trying out the fix I provided both for windows and the raspberry?

**Comment by USW-Adam** [comment]
Yeah tried out the fix worked on both windows and raspberry pi

**Comment by spacemanspiff2007** [comment]
Thank you very much for your help!
